### ISSUE TITLE
Chat box has an irregular shape

### ISSUE THREAD

**Issue by felipe1982** [paul-norman/bga-css#1]
Thanks for creating this CSS. It looks amazing - and very long.

I have been enjoying it, and looking forward to trying it on mobile soon.

I found one problem when using MIcrosoft Edge (Chromium version). The chat box has a strange shape. The example here is in the game "Hearts" but appears on all other games too.

![image](https://user-images.githubusercontent.com/275621/125370805-a8cb7a00-e3c2-11eb-86d8-674be5b8d767.png)

**Comment by paul-norman** [comment]
This should now be fixed.
