### ISSUE TITLE
Tokaido Souvenirs looks a bit skewed

### ISSUE THREAD

**Issue by felipe1982** [paul-norman/bga-css#2]
![image](https://user-images.githubusercontent.com/275621/125385246-7e3aea80-e3dd-11eb-8317-37e30e756063.png)

https://boardgamearena.com/gamepanel?game=tokaido&howtoplay_seemore

**Comment by paul-norman** [comment]
Not sure how I've managed to screw that up, but I'll look at it after dinner...

**Comment by paul-norman** [comment]
This should now also be fixed, used the wrong selector to put box-sizing back to BGA defaults in game...
